# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 875)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backwardButton = QtWidgets.QPushButton(self.centralwidget)
        self.backwardButton.setGeometry(QtCore.QRect(320, 710, 120, 40))
        self.backwardButton.setObjectName("backwardButton")
        self.forwardButton = QtWidgets.QPushButton(self.centralwidget)
        self.forwardButton.setGeometry(QtCore.QRect(450, 710, 120, 40))
        self.forwardButton.setObjectName("forwardButton")
        self.deviceBox = QtWidgets.QComboBox(self.centralwidget)
        self.deviceBox.setGeometry(QtCore.QRect(320, 40, 250, 20))
        self.deviceBox.setObjectName("deviceBox")
        self.deviceBoxLabel = QtWidgets.QLabel(self.centralwidget)
        self.deviceBoxLabel.setGeometry(QtCore.QRect(320, 20, 260, 20))
        self.deviceBoxLabel.setObjectName("deviceBoxLabel")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(319, 210, 251, 70))
        self.lcdNumber.setLineWidth(1)
        self.lcdNumber.setMidLineWidth(0)
        self.lcdNumber.setDigitCount(7)
        self.lcdNumber.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber.setObjectName("lcdNumber")
        self.measurementLabel = QtWidgets.QLabel(self.centralwidget)
        self.measurementLabel.setGeometry(QtCore.QRect(320, 130, 250, 70))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.measurementLabel.setFont(font)
        self.measurementLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.measurementLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.measurementLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.measurementLabel.setObjectName("measurementLabel")
        self.rightTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.rightTableWidget.setGeometry(QtCore.QRect(30, 70, 272, 743))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rightTableWidget.setFont(font)
        self.rightTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rightTableWidget.setShowGrid(True)
        self.rightTableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.rightTableWidget.setRowCount(36)
        self.rightTableWidget.setColumnCount(3)
        self.rightTableWidget.setObjectName("rightTableWidget")
        self.rightTableWidget.horizontalHeader().setVisible(True)
        self.rightTableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.rightTableWidget.verticalHeader().setVisible(False)
        self.rightTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.rightTableWidget.verticalHeader().setDefaultSectionSize(18)
        self.rightTableWidget.verticalHeader().setMinimumSectionSize(20)
        self.leftLNumberInput = QtWidgets.QLineEdit(self.centralwidget)
        self.leftLNumberInput.setGeometry(QtCore.QRect(320, 450, 120, 20))
        self.leftLNumberInput.setObjectName("leftLNumberInput")
        self.rightLNumberInput = QtWidgets.QLineEdit(self.centralwidget)
        self.rightLNumberInput.setGeometry(QtCore.QRect(450, 450, 120, 20))
        self.rightLNumberInput.setObjectName("rightLNumberInput")
        self.leftMonitorLabel = QtWidgets.QLabel(self.centralwidget)
        self.leftMonitorLabel.setGeometry(QtCore.QRect(320, 290, 120, 120))
        self.leftMonitorLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.leftMonitorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.leftMonitorLabel.setObjectName("leftMonitorLabel")
        self.rightMonitorLabel = QtWidgets.QLabel(self.centralwidget)
        self.rightMonitorLabel.setGeometry(QtCore.QRect(450, 290, 120, 120))
        self.rightMonitorLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.rightMonitorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rightMonitorLabel.setObjectName("rightMonitorLabel")
        self.leftLNumberLabel = QtWidgets.QLabel(self.centralwidget)
        self.leftLNumberLabel.setGeometry(QtCore.QRect(320, 420, 120, 20))
        self.leftLNumberLabel.setObjectName("leftLNumberLabel")
        self.rightLNumberLabel = QtWidgets.QLabel(self.centralwidget)
        self.rightLNumberLabel.setGeometry(QtCore.QRect(450, 420, 120, 20))
        self.rightLNumberLabel.setObjectName("rightLNumberLabel")
        self.rightPvmLabel = QtWidgets.QLabel(self.centralwidget)
        self.rightPvmLabel.setGeometry(QtCore.QRect(450, 480, 120, 20))
        self.rightPvmLabel.setObjectName("rightPvmLabel")
        self.leftLPvmInput_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.leftLPvmInput_2.setGeometry(QtCore.QRect(320, 510, 120, 20))
        self.leftLPvmInput_2.setObjectName("leftLPvmInput_2")
        self.rightLPvmInput = QtWidgets.QLineEdit(self.centralwidget)
        self.rightLPvmInput.setGeometry(QtCore.QRect(450, 510, 120, 20))
        self.rightLPvmInput.setObjectName("rightLPvmInput")
        self.leftPvmLabel = QtWidgets.QLabel(self.centralwidget)
        self.leftPvmLabel.setGeometry(QtCore.QRect(320, 480, 120, 20))
        self.leftPvmLabel.setObjectName("leftPvmLabel")
        self.leftMittaajaLabel = QtWidgets.QLabel(self.centralwidget)
        self.leftMittaajaLabel.setGeometry(QtCore.QRect(320, 540, 120, 20))
        self.leftMittaajaLabel.setObjectName("leftMittaajaLabel")
        self.rightMittaajaLabel = QtWidgets.QLabel(self.centralwidget)
        self.rightMittaajaLabel.setGeometry(QtCore.QRect(450, 540, 120, 20))
        self.rightMittaajaLabel.setObjectName("rightMittaajaLabel")
        self.leftLMittaajaInput = QtWidgets.QLineEdit(self.centralwidget)
        self.leftLMittaajaInput.setGeometry(QtCore.QRect(320, 570, 120, 20))
        self.leftLMittaajaInput.setObjectName("leftLMittaajaInput")
        self.rightLMittaajaInput = QtWidgets.QLineEdit(self.centralwidget)
        self.rightLMittaajaInput.setGeometry(QtCore.QRect(450, 570, 120, 20))
        self.rightLMittaajaInput.setObjectName("rightLMittaajaInput")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(320, 630, 121, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.themeBox = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.themeBox.setContentsMargins(0, 0, 0, 0)
        self.themeBox.setObjectName("themeBox")
        self.themeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.themeLabel.setObjectName("themeLabel")
        self.themeBox.addWidget(self.themeLabel)
        self.lightThemeButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.lightThemeButton.setObjectName("lightThemeButton")
        self.themeBox.addWidget(self.lightThemeButton)
        self.darkThemeButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.darkThemeButton.setObjectName("darkThemeButton")
        self.themeBox.addWidget(self.darkThemeButton)
        self.leftMonitorSelect = QtWidgets.QPushButton(self.centralwidget)
        self.leftMonitorSelect.setGeometry(QtCore.QRect(30, 20, 91, 51))
        self.leftMonitorSelect.setObjectName("leftMonitorSelect")
        self.leftTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.leftTableWidget.setGeometry(QtCore.QRect(30, 70, 272, 743))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leftTableWidget.setFont(font)
        self.leftTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.leftTableWidget.setShowGrid(True)
        self.leftTableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.leftTableWidget.setRowCount(36)
        self.leftTableWidget.setColumnCount(3)
        self.leftTableWidget.setObjectName("leftTableWidget")
        self.leftTableWidget.horizontalHeader().setVisible(True)
        self.leftTableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.leftTableWidget.verticalHeader().setVisible(False)
        self.leftTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.leftTableWidget.verticalHeader().setDefaultSectionSize(18)
        self.leftTableWidget.verticalHeader().setMinimumSectionSize(20)
        self.rightMonitorSelect = QtWidgets.QPushButton(self.centralwidget)
        self.rightMonitorSelect.setGeometry(QtCore.QRect(120, 20, 91, 51))
        self.rightMonitorSelect.setObjectName("rightMonitorSelect")
        self.rightMonitorSelect_2 = QtWidgets.QPushButton(self.centralwidget)
        self.rightMonitorSelect_2.setGeometry(QtCore.QRect(210, 20, 92, 72))
        self.rightMonitorSelect_2.setObjectName("rightMonitorSelect_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Monitorimittari"))
        self.backwardButton.setText(_translate("MainWindow", "Edellinen [Backspace]"))
        self.forwardButton.setText(_translate("MainWindow", "Seuraava [Enter]"))
        self.deviceBoxLabel.setText(_translate("MainWindow", "Valitse laite"))
        self.measurementLabel.setText(_translate("MainWindow", "Mittaus"))
        self.leftMonitorLabel.setText(_translate("MainWindow", "VASEN MONITORI"))
        self.rightMonitorLabel.setText(_translate("MainWindow", "OIKEA MONITORI"))
        self.leftLNumberLabel.setText(_translate("MainWindow", "L-Numero"))
        self.rightLNumberLabel.setText(_translate("MainWindow", "L-Numero"))
        self.rightPvmLabel.setText(_translate("MainWindow", "Pvm"))
        self.leftPvmLabel.setText(_translate("MainWindow", "Pvm"))
        self.leftMittaajaLabel.setText(_translate("MainWindow", "Mittaaja(t)"))
        self.rightMittaajaLabel.setText(_translate("MainWindow", "Mittaaja(t)"))
        self.themeLabel.setText(_translate("MainWindow", "Theme"))
        self.lightThemeButton.setText(_translate("MainWindow", "Light"))
        self.darkThemeButton.setText(_translate("MainWindow", "Dark"))
        self.leftMonitorSelect.setText(_translate("MainWindow", "Vasen"))
        self.rightMonitorSelect.setText(_translate("MainWindow", "Oikea"))
        self.rightMonitorSelect_2.setText(_translate("MainWindow", "Muokkaa kaikkia"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

